### ISSUE TITLE
Add support for arm64 machine

### ISSUE THREAD

**Issue by WasinWatt** [iboss-ptk/terrain#11]
On a regular arm64 machine, terra suggests to use cosmwasm/rust-optimizer-arm64:0.12.4 as the docker image for optimization which will produce an artifact at `artifacts/<contract-name>-aarch64.wasm` which is different from non-arm one. Right now `terrain` doesn't support this option which results in a failure after `terrain deploy` command.

**Comment by octalmage** [comment]
I'm working on this right now! thanks for the report!

**Comment by iboss-ptk** [comment]
support the option in v0.0.9

**Comment by vyuldashev** [comment]
Getting the following error after an upgrade:

```
cp: artifacts/contract-aarch64.wasm: No such file or directory
Error: Command failed: cp artifacts/contract{-aarch64,}.wasm
cp: artifacts/contract-aarch64.wasm: No such file or directory
```

`terrain deploy` still generates `contract.wasm` file.

**Comment by RodionChachura** [comment]
Hey @octalmage!

I'm on Apple M1 Pro and have this issue with the latest `terrain` 🤷‍♂️
```bash
terrain -v
@iboss/terrain/0.0.9 darwin-arm64 node-v16.14.2
```

Running `terrain deploy counter --signer test1` on the sample project crashes here
```bash
Finished, status of exit status: 0
cp: artifacts/counter-aarch64.wasm: No such file or directory
    Error: Command failed: cp artifacts/counter{-aarch64,}.wasm
    cp: artifacts/counter-aarch64.wasm: No such file or directory
```

Docker preferences 👇

<img width="483" alt="image" src="https://user-images.githubusercontent.com/17750556/161430230-4d37569a-4791-4379-94cb-c196cbcca9b5.png">

**Comment by RodionChachura** [comment]
Reversing to 0.0.8 did help https://github.com/iboss-ptk/terrain/issues/30
