### ISSUE TITLE
Issue with using await in terrain console

### ISSUE THREAD

**Issue by pkayfire** [iboss-ptk/terrain#14]
<img width="431" alt="image" src="https://user-images.githubusercontent.com/2524873/148166738-9e29ad9a-eee8-48e7-891b-d6a070bf7410.png">

Getting the above error when using `await` in the terrain console.

**Comment by iboss-ptk** [comment]
I have never face that issue myself, could you let me know the env you are on? (nodejs version, os)

**Comment by WasinWatt** [comment]
Top-level await has been enabled by default since node 16.6.0. Probably need to bump your node version @pkayfire .
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V16.md#16.13.1
