### ISSUE TITLE
provide link to github repo in help

### ISSUE THREAD

**Issue by petes-fan-club** [iboss-ptk/terrain#5]
for people who are using this and keep forgetting where your repo is ;-)

**Comment by iboss-ptk** [comment]
@petes-fan-club could you please elaborate where to provide link?

**Comment by petes-fan-club** [comment]
In the CLI. Ideally in the usage

**Comment by iboss-ptk** [comment]
Good idea! Thank you :)

**Comment by vtno** [comment]
@iboss-ptk I can take this if you don't mind.
