### ISSUE TITLE
Since i saw you last my love.... 

### ISSUE THREAD

**Issue by WelcometoOz** [iboss-ptk/terrain#6]
For as long as i can remember, ive always wanted to be a gangster .... Shaved heads , white T's ,  feel thats Cali breeze, Bitch on your knees, hands in the air, we aint asking twice , first time wasnt so nice. Beans and rice....  Surenos fo life.... To all the gente behind bars , or serving sentence  on the streets , hood row., Here we go , locked n loaded. Cream. Found, goonz..

**Comment by iboss-ptk** [comment]
unrelated topic
